config/routes.rb
Rails.application.routes.draw do
  resources :anagrams
  root :to => 'anagrams#index' 
end

app/models/anagram.rb
class Anagram < ActiveRecord::Base
end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  before_action :set_anagram, only: [:show]
  # GET /anagrams
  # GET /anagrams.json
  def index
    @anagrams = Anagram.all
  end

  # GET /anagrams/1
  # GET /anagrams/1.json
  def show
  end

  # GET /anagrams/new
  def new
    @anagram = Anagram.new
  end

  # POST /anagrams
  # POST /anagrams.json
  def create
    @anagram = Anagram.new(anagram_params)
    @anagram.result = anagramChecker(@anagram.w1,@anagram.w2)
    respond_to do |format|
      if @anagram.save
        format.html { redirect_to @anagram, notice: 'Anagram check request was successfully stored.' }
        format.json { render :show, status: :created, location: @anagram }
      else
        format.html { render :new }
        format.json { render json: @anagram.errors, status: :unprocessable_entity }
      end
    end
  end

  def anagramChecker(w1,w2)
    w1 = w1.downcase
    w2 = w2.downcase
    w_a1 = w1.split(//);
    w_a2 = w2.split(//);
    
    if w_a1.sort == w_a2.sort
      return true
    end
    
    return false
  end
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_anagram
    @anagram = Anagram.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def anagram_params
    params.require(:anagram).permit(:w1, :w2, :result)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/anagrams_helper.rb
module AnagramsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anagrams/_form.html.erb
<%= form_for(@anagram) do |f| %>
<% if @anagram.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@anagram.errors.count, "error") %> prohibited this anagram from being saved:</h2>

	<ul>
		<% @anagram.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div align="center">
	<div class="field">
		<%= f.label 'Word 1	' %>
		<br>
		<%= f.text_field :w1 %>
	</div>
	<div class="field">
		<%= f.label 'Word 2' %>
		<br>
		<%= f.text_field :w2 %>
	</div>
	<div class="actions">
		<%= f.submit "is Anagram?"%>
	</div>
</div>
<% end %>

app/views/anagrams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anagrams Detector</h1>
</ br>
</ br>
</ br>


<div id="navigation_container">
 

 
      <div class="rectangle">
 
<!-- the navigation links -->
 
   <ul id="navigation">
      <li><%= link_to 'Check New Anagram', new_anagram_path %></li>
   </ul>

   </div>
 

<!-- end container -->
</div>


<table align="center">
  <thead>
    <tr>
      <th>Word 1</th>
      <th>Word 2</th>
      <th>Result</th>
      <th colspan="30"></th>
    </tr>
  </thead>

  <tbody>
    <% @anagrams.each do |anagram| %>
      <tr>
        <td><%= anagram.w1 %></td>
        <td><%= anagram.w2 %></td>
        <td><%= anagram.result %></td>
        <td><%= link_to 'Show', anagram %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<footer>
	<div class="container">
		RD test, Anagram detector
	</div>
</footer>

app/views/anagrams/new.html.erb
<h1>Check Anagram</h1>
</ br>
</ br>
</ br>

<div id="navigation_container">

	<div class="rectangle">

		<ul id="navigation">

			<li>
				<ul id="home">
					<%= link_to '__Home__', anagrams_path %></ud
			</li>
		</ul>

	</div>

</div>

<%= render 'form' %>

<footer>
	<div class="container">
		RD test, Anagram detector
	</div>
</footer>

app/views/anagrams/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Anagrams Detector</h1>
</ br>
</ br>
</ br>

<div id="navigation_container">

	<div class="rectangle">

		<ul id="navigation">
			<li>
				<%= link_to 'Check New Anagram', new_anagram_path %>
			</li>
		</ul>

	</div>

</div>

<p>
	<strong>Word 1:</strong>
	<%= @anagram.w1 %>
</p>

<p>
	<strong>Word 2:</strong>
	<%= @anagram.w2 %>
</p>

<p>
	<strong>Result:</strong>
	<%= @anagram.result %>
</p>
<p>
	<strong>Request date:</strong>
	<%= @anagram.created_at %>
</p>

<div id="navigation_container">

	<div class="rectangle">

		<ul id="navigation">

			<li>
				<ul id="home">
					<%= link_to '__Home__', anagrams_path %></ud
			</li>
		</ul>

	</div>

</div>

<footer>
	<div class="container">
		RD test, Anagram detector
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnagramChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>